### ISSUE TITLE
New annotations

### ISSUE THREAD

**Issue by chb0github** [malkusch/validation#4]
I would like to donate a few new validations. Are you still alive and taking pull requests?

**Comment by malkusch** [comment]
Sure I will accept contributions.

**Comment by chb0github** [comment]
I have added 
TimeZone
Currency
UUID

And I have updated Country to be based on actual country codes listed by the system. 

I could like to recomment changing `@Country` to `CountryCode` as it's more precise. `@Country` initially lead me to thing 'United States'

**Comment by chb0github** [comment]
Can I get this merged in? All tests pass, I conform pretty nicely with the coding style you have and I provided message templates (in English). Sorry, I don't know German. I Do know some other languages though.

**Comment by chb0github** [comment]
Do you want to actually do this PR? Because I would like to get these new validations. If I must I will rename all the packages and release under my own artifact id.
